[http_server]
insecure_http = true

[attestation_token]
insecure_key = true

[attestation_service]
type = "coco_as_grpc"
as_addr = "http://127.0.0.1:50004"
pool_size = 200

[admin]
# Do not use this in production.
type = "InsecureAllowAll"

[storage_backend]
storage_type = "LocalFs"

[storage_backend.backends.local_fs]
dir_path = "/opt/confidential-containers/storage"

[[plugins]]
name = "resource"
backend = "kvstorage"
