[package]
name = "key-value-storage"
version = "0.1.0"
edition = "2021"

[features]
default = ["postgres"]
postgres = ["sqlx/postgres", "pg-connection-string"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
pg-connection-string = { version = "0.0.2", optional = true }
educe.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.8.6", features = [
    "postgres",
    "runtime-tokio",
], optional = true }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
rstest.workspace = true
tempfile.workspace = true
tokio.workspace = true
toml.workspace = true
