[http_server]
insecure_http = true

[attestation_token]
insecure_key = false

[attestation_service]
type = "coco_as_builtin"
timeout = 5

[attestation_service.attestation_token_broker]
duration_min = 5

[attestation_service.rvps_config]
type = "BuiltIn"

[storage_backend]
storage_type = "LocalJson"
backends.local_json.file_dir_path = "/opt/confidential-containers/trustee"

[admin]
type = "Simple"

[[plugins]]
name = "resource"
backend = "kvstorage"
