[attestation_token]
trusted_certs_paths = ["/etc/ca", "/etc/ca2"]

[attestation_service]
type = "coco_as_grpc"
as_addr = "http://127.0.0.1:50001"
pool_size = 100
timeout = 600

[http_server]
sockets = ["0.0.0.0:8080"]
private_key = "/etc/kbs-private.key"
certificate = "/etc/kbs-cert.pem"
insecure_http = false

[admin]
type = "DenyAll"

[policy_engine]
policy_path = "/etc/kbs-policy.rego"

[[plugins]]
name = "sample"
item = "value1"

[[plugins]]
name = "resource"
type = "LocalFs"
dir_path = "/tmp/kbs-resource"
