[http_server]
insecure_http = true

[attestation_token]
insecure_key = false

[attestation_service]
type = "coco_as_builtin"
work_dir = "/opt/confidential-containers/attestation-service"
timeout = 5

[attestation_service.attestation_token_broker]
duration_min = 5

[attestation_service.attestation_token_broker.policy_engine.storage]
type = "LocalJson"
file_path = "/opt/confidential-containers/attestation-service/ear-policies.json"

[attestation_service.rvps_config]
type = "BuiltIn"

[attestation_service.rvps_config.storage]
type = "LocalFs"

[policy_engine.storage]
type = "LocalJson"
file_path = "/opa/confidential-containers/kbs/policy.json"

[admin]
type = "Simple"

[[plugins]]
name = "resource"
backend = "kvstorage"
type = "LocalFs"
dir_path = "/opt/confidential-containers/kbs/repository"
