[attestation_token]
trusted_jwk_sets = ["/etc/ca", "/etc/ca2"]

[attestation_service]
type = "intel_ta"
base_url = "example.io"
api_key = "this-is-a-key"
certs_file = "file:///etc/ita-cert.pem"
allow_unmatched_policy = true
timeout = 5

[http_server]
sockets = ["0.0.0.0:8080"]
private_key = "/etc/kbs-private.key"
certificate = "/etc/kbs-cert.pem"
insecure_http = false

[admin]
type = "DenyAll"

[storage_backend]
storage_type = "local_json"
backends.local_json.file_dir_path = "/opt/confidential-containers/trustee"

[[plugins]]
name = "sample"
item = "value1"

[[plugins]]
name = "resource"
backend = "kvstorage"
