apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coco-tenant

resources:
- ../base

patches:
- path: patch.yaml
  target:
    group: apps
    kind: Deployment
    name: kbs
    version: v1

# Store keys that KBS will release to workloads after attestation:
# kbs:///reponame/workload_key/key.bin
secretGenerator:
- files:
  - key.bin
  name: keys
