name: Actionlint
on: [pull_request]
permissions:
  contents: read

jobs:
  actionlint:
    name: Workflow Files
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
      with:
        fail_on_error: true
