name: Cut Release

on:
  release:
    types: [published]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Build and push attestation-service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.as
          platforms: linux/amd64
          push: true
          tags: ghcr.io/confidential-containers/attestation-service:latest, ghcr.io/confidential-containers/attestation-service:${{ github.ref_name }}
      -
        name: Build and push reference-value-provider-service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.rvps
          platforms: linux/amd64
          push: true
          tags: ghcr.io/confidential-containers/reference-value-provider-service:latest, ghcr.io/confidential-containers/reference-value-provider-service:${{ github.ref_name }}